version: "3.9"

services:
  hwanee-db:
    image: mysql:lastest
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1111
      - MYSQL_DATABASE=jpastart
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin -uroot -p1111 ping -h localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - board

  board:
    depends_on:
      hwanee-db:
        condition: service_healthy
    build: .
    ports:
      - "8080:8080"
    networks:
      - board


volumes:
  db: {}

networks:
  board: {}